import { execFileSync } from 'node:child_process';
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

const output = path.resolve(import.meta.dirname, '../../../.audit-results', new Date().toISOString().replace(/[:.]/g, '-'));
await mkdir(output, { recursive: true });
const cli = process.env.MUSIC_AGENT_BROWSER || 'agent-browser';
const args = ['--session', process.env.MUSIC_AUDIT_SESSION || 'music-regressions'];
let started = false;
const run = (...command) => {
  const env = { ...process.env };
  if (started) delete env.AGENT_BROWSER_EXECUTABLE_PATH;
  started = true;
  if (['click', 'focus'].includes(command[0]) && ['Library', 'Library filters', 'Layout', 'Background', 'Theme'].some(label => command[1] === `button[aria-label="${label}"]`)) {
    const expanded = execFileSync(cli, [...args, 'eval', 'document.querySelector(".bar-modes > button").getAttribute("aria-expanded")'], { encoding: 'utf8', timeout: 30000, env }).trim();
    if (!expanded.includes('true')) execFileSync(cli, [...args, 'click', 'button[aria-label="Choose toolbar mode"]'], { encoding: 'utf8', timeout: 30000, env });
  }
  return execFileSync(cli, [...args, ...command], { encoding: 'utf8', timeout: 30000, env });
};
const evaluate = code => run('eval', code);
const assert = (condition, message) => evaluate(`(() => { if (!(${condition})) throw new Error(${JSON.stringify(message)}); return 'PASS'; })()`);
const button = name => `button[aria-label="${name}"]`;
const capture = (size, name) => run('screenshot', path.join(output, `${size}-${name}.png`));
const clickBarBackground = () => {
  const [x, y] = JSON.parse(evaluate(`(() => { const r=document.querySelector('.bar-toggle').getBoundingClientRect(); return [r.left+8,r.top+r.height/2]; })()`));
  assert(`document.elementFromPoint(${x},${y})?.classList.contains('bar-toggle')`, 'The left edge of the playback bar must reach its full-width background target');
  run('mouse', 'move', String(x), String(y));
  run('mouse', 'down'); run('mouse', 'up');
};
const results = [];
try {
  const viewports = [[1920,1080], [1440,900], [1024,768], [390,844]].filter(([width, height]) => !process.env.MUSIC_AUDIT_VIEWPORT || process.env.MUSIC_AUDIT_VIEWPORT === `${width}x${height}`);
  if (!viewports.length) throw new Error('Unknown MUSIC_AUDIT_VIEWPORT');
  for (const [width, height] of viewports) {
    const size = `${width}x${height}`;
    run('set', 'viewport', String(width), String(height));
    run('open', process.env.MUSIC_AUDIT_URL || `http://127.0.0.1:${process.env.MUSIC_AUDIT_PORT || 4178}`);
    run('wait', '.tile-wrap');
    run('mouse', 'move', '0', '0');
    run('wait', '200');
    assert(`getComputedStyle(document.querySelector('.tile-info')).opacity === '0'`, 'Details must be hidden initially');
    evaluate('document.activeElement?.blur()');
    run('mouse', 'move', String(width / 2), String(height / 2));
    run('wait', '3200');
    run('hover', '.tile-wrap:first-child');
    run('wait', '200');
    assert(`getComputedStyle(document.querySelector('.tile-info')).opacity === '1'`, 'Hover must reveal details');
    assert(`(() => { const el=document.querySelector('.tile-play button'); const r=el.getBoundingClientRect(); return el.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2)); })()`, 'Artwork must not obscure the separate play action');
    run('mouse', 'move', '0', '0');
    run('focus', '.tile-wrap:first-child .tile-play button');
    run('wait', '200');
    assert(`getComputedStyle(document.querySelector('.tile-info')).opacity === '1'`, 'Keyboard focus must reveal details');
    capture(size, 'card-focus');
    evaluate('document.activeElement?.blur()');
    run('mouse', 'move', String(width / 2), String(height / 2));
    run('wait', '3200');
    run('click', '.tile-wrap:first-child .tile');
    run('wait', '.album-view');
    assert(`!window.__auditCommands.some(c=>c[0]==='play') && document.querySelector('.album-view .detail-cover')`, 'Cover must open album details without starting playback');
    capture(size, 'album-details');
    run('click', button('Back to music'));
    run('hover', '.tile-wrap:first-child');
    run('click', '.tile-wrap:first-child .tile-play button');
    run('wait', '--fn', '!!document.querySelector(".tile-wrap.listening")');
    assert(`window.__auditCommands.some(c=>c[0]==='play') && document.querySelector('.tile-wrap.listening .listening')`, 'Separate play must start included tracks and show the listening icon');
    run('click', '.bar .btns button[aria-label="Pause"]');
    run('wait', '--fn', '!!document.querySelector(".bar .btns button[aria-label=Play]")');
    assert(`!document.querySelector('.now-playing')`, 'Transport must control playback without opening the player');
    run('focus', '.bar-toggle');
    clickBarBackground();
    run('wait', '.now-playing');
    assert(`document.querySelector('.now-playing .detail-cover') !== null`, 'The full-width bar target must open now playing with large artwork');
    assert(`getComputedStyle(document.querySelector('.bar')).getPropertyValue('--play-surface').trim() !== ''`, 'Player must share its artwork palette');
    assert(`document.documentElement.scrollWidth<=innerWidth`, 'Now playing must fit the viewport');
    capture(size, 'now-playing');
    run('click', '.now-playing button[popovertarget="queue-actions-0"]');
    assert(`!!document.querySelector('.now-playing [popover]:popover-open')`, 'Track actions must open on demand');
    run('press', 'Escape');
    assert(`document.querySelector('.now-playing') && !document.querySelector('.now-playing [popover]:popover-open')`, 'Escape must close track actions before the player');
    run('press', 'Escape');
    run('wait', '--fn', '!document.querySelector(".now-playing")');
    const returnedFocus = run('eval', 'document.activeElement.outerHTML').trim();
    assert(`!document.querySelector('.now-playing') && document.activeElement.classList.contains('bar-toggle')`, `Escape must close now playing and restore its opening bar control; active=${returnedFocus}`);

    evaluate('document.activeElement?.blur()');
    run('press', 'ArrowRight');
    run('wait', '350');
    assert(`document.querySelector('.bar .meta b').textContent.includes('song 2')`, 'Right arrow must advance playback');
    run('press', 'ArrowLeft');
    run('wait', '350');
    assert(`document.querySelector('.bar .meta b').textContent.includes('song 1')`, 'Left arrow must return to the previous track');
    run('click', button('Pause'));
    evaluate('document.activeElement?.blur()');
    run('press', '/');
    run('wait', '200');
    assert(`document.activeElement.getAttribute('aria-label')==='Search library'`, 'Slash must reveal and focus search');
    run('press', 'q');
    assert(`document.activeElement.value==='q' && !document.querySelector('.now-playing')`, 'Typing shortcuts must enter text rather than open views');
    run('press', 'Escape');
    assert(`document.activeElement.value===''`, 'Escape in search must clear the query first');
    run('press', 'Escape');
    assert(`document.activeElement.getAttribute('aria-label')!=='Search library'`, 'Escape in empty search must exit it');
    evaluate('document.activeElement?.blur()');
    run('press', 'Control+k');
    assert(`document.activeElement.getAttribute('aria-label')==='Search library'`, 'Control K must focus search');
    run('press', 'Escape');
    evaluate('document.activeElement?.blur()');
    run('press', 'q');
    run('wait', '300');
    assert(`!!document.querySelector('.now-playing')`, 'Q must open the player');
    run('click', '#player-tab-history');
    run('wait', '400');
    assert(`document.querySelectorAll('.recent-song').length>=3 && document.querySelector('.recent-song').innerText.includes('Album')`, 'SQLite history must retain playback origins');
    run('fill', '[aria-label="Search listening history"]', 'no-such-song');
    run('wait', '400');
    assert(`!document.querySelector('.recent-song') && document.body.innerText.includes('No plays match')`, 'History search must show a useful no-match state');
    run('fill', '[aria-label="Search listening history"]', 'Included');
    run('wait', '400');
    assert(`document.querySelectorAll('.recent-song').length>=3`, 'History full-text search must restore matching plays');
    capture(size, 'sqlite-history');
    run('click', '#player-tab-queue');
    run('press', 'Escape');
    run('wait', '200');
    evaluate('document.activeElement?.blur()');
    run('press', 's');
    run('wait', '300');
    assert(`document.querySelector('.settings-dialog[open] h1')?.textContent==='Settings'`, 'S must open Settings');
    run('press', 'Escape');
    run('wait', '200');
    assert(`!document.querySelector('.settings-dialog[open]')`, 'Escape must close Settings');
    run('press', '?');
    assert(`!!document.querySelector('[aria-label="Keyboard shortcuts"]')`, 'Shortcut help must be discoverable');
    capture(size, 'keyboard-help');
    run('press', 'Escape');
    run('click', button('Menu'));
    run('focus', 'button[aria-label="Playback options"]');
    run('press', 'ArrowDown');
    assert(`document.activeElement.closest('#playback-options')!==null`, 'Playback options arrow key must open and focus its menu');
    run('press', 'End');
    assert(`document.activeElement.getAttribute('aria-label')==='Random from the grid'`, 'End must focus the last playback option');
    run('press', 'Escape');
    assert(`document.activeElement.getAttribute('aria-label')==='Playback options' && document.querySelector('.now-playing')`, 'Playback menu Escape must restore its trigger without closing the player');
    run('press', 'Escape');
    assert(`document.activeElement.getAttribute('aria-label')==='Menu'`, 'Closing the player must restore the bottom menu trigger');
    const commandsBeforeDiscovery = run('eval', 'window.__auditCommands.length').trim();
    run('mouse', 'move', String(width / 2), '35');
    run('wait', '350');
    assert(`!document.querySelector('.browse').classList.contains('hidden')`, 'Approaching the top edge must reveal the toolbar before reaching the edge');
    run('click', button('Dig into your music'));
    run('click', '.presets button:first-child');
    assert(`document.querySelector('.discovered') !== null && window.__auditCommands.length === ${commandsBeforeDiscovery}`, 'Discovery must reveal a cover without starting playback');
    run('click', button('Dig into your music'));
    const playingBeforeViews = run('eval', 'document.querySelector(".bar .meta").innerText').trim();
    run('fill', '[aria-label="Collection type"]', 'Playlists');
    run('click', '[role="option"]');
    run('wait', '.tile[aria-label^="Open Liked Songs"]');
    assert(`document.querySelector('[aria-label="Collection type"]').value==='Playlists' && document.querySelector('.bar .meta').innerText===${playingBeforeViews}`, 'Switching to playlists must preserve playback');
    capture(size, 'playlists');
    run('fill', '[aria-label="Collection type"]', 'Albums');
    run('click', '[role="option"]');
    run('wait', '--fn', 'document.querySelectorAll(".tile-wrap").length>10');

    assert(`document.querySelector('.compact-bar').getBoundingClientRect().right<=innerWidth && document.querySelectorAll('[aria-label="Search library"]').length===1`, 'The compact toolbar must fit the viewport and keep one search field');
    run('click', button('Choose toolbar mode'));
    assert(`document.querySelector('[aria-label="Choose toolbar mode"]').getAttribute('aria-expanded')==='true' && !document.querySelector('.mode-options').inert`, 'Selector must expose its mode choices');
    assert(`(() => { const menu=document.querySelector('.mode-options').getBoundingClientRect(); const trigger=document.querySelector('[aria-label="Choose toolbar mode"]').getBoundingClientRect(); return menu.left>=0 && menu.right<=innerWidth && menu.top>=trigger.bottom && menu.bottom<=innerHeight; })()`, 'Mode choices must open below the trigger within the viewport');
    run('mouse', 'move', String(width / 2), String(height / 2));
    run('wait', '3200');
    assert(`!document.querySelector('.browse').classList.contains('hidden')`, 'Open selector must pin the toolbar after pointer departure');
    run('click', button('Choose toolbar mode'));
    assert(`!document.querySelector('[aria-label="Filter by artist"]')`, 'Secondary filters must be hidden initially');
    run('click', button('Library filters'));
    run('fill', '[aria-label="Filter by artist"]', 'zzzz-no-artist');
    run('wait', '100');
    assert(`document.querySelector('[aria-label="Filter by artist"]').getAttribute('aria-expanded')==='true' && document.body.innerText.includes('No matches')`, 'Typing must open no-match results');
    run('press', 'Escape');
    assert(`document.querySelector('[aria-label="Filter by artist"]').value==='All artists'`, 'Escape must restore the selected label');
    run('fill', '[aria-label="Filter by artist"]', 'Bowie');
    capture(size, 'artist-dropdown');
    run('click', '[role="option"]');
    assert(`document.querySelector('[aria-label="Filter by artist"]').value==='David Bowie'`, 'Artist selection must apply');
    run('click', '.filter-tray [data-slot="button"]');
    run('click', button('Settings'));
    run('wait', '500');
    assert(`document.querySelector(${JSON.stringify(button('Settings'))}).getAttribute('aria-pressed')==='true'`, 'Settings must show selected state');
    capture(size, 'settings');
    assert(`document.querySelector('.settings-dialog h2')?.textContent==='Appearance'`, 'Everyday appearance controls must come first');
    assert(`Array.from(document.querySelectorAll('.settings-dialog details')).every(details=>!details.open)`, 'Secondary settings must start collapsed');
    assert(`(() => { const dialog=document.querySelector('.settings-dialog'); const r=dialog.getBoundingClientRect(); return dialog.matches(':modal') && r.left>=0 && r.right<=innerWidth && r.top>=0 && r.bottom<=innerHeight && Math.abs(r.x+r.width/2-innerWidth/2)<1 && Math.abs(r.y+r.height/2-innerHeight/2)<1; })()`, 'Settings must be a centered modal bounded by the viewport');
    run('focus', '#settings-tab-appearance');
    run('press', 'ArrowRight');
    assert(`document.activeElement.id==='settings-tab-spotify' && document.activeElement.getAttribute('aria-selected')==='true'`, 'Settings arrows must focus and select categories');
    capture(size, 'settings-spotify');
    assert(`document.querySelectorAll('.connection .account button').length===1 && document.querySelector('.connection .account').innerText.includes('Test account') && document.querySelector('.connection .account button').innerText==='Disconnect'`, 'Spotify must show Disconnect beside the current username');
    assert(`document.querySelector('.connection-status').innerText.includes('Connected · Playback ready')`, 'Ready Spotify output must be explicit');
    evaluate(`window.__auditSpotifyStatus({availability:'device-unavailable'})`);
    assert(`!document.querySelector('.connection-status').innerText.includes('Playback ready') && document.querySelector('.spotify-settings').innerText.includes('Spotify playback output unavailable')`, 'An unavailable output must not claim playback is ready');
    evaluate(`window.__auditSpotifyStatus({availability:'ready'})`);
    run('click', '[aria-label="Open Spotify playback device"]');
    assert(`(() => { const option=document.querySelector('[role=option]'); const r=option.getBoundingClientRect(); return !!option.closest('dialog') && option.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2)); })()`, 'Spotify device options must be clickable above the modal backdrop');
    capture(size, 'settings-devices');
    run('press', 'Escape');
    run('wait', '--fn', '!document.querySelector("[role=listbox]")');
    assert(`!!document.querySelector('.settings-dialog[open]')`, 'Escape must close the device picker before Settings');
    run('fill', '[aria-label="Spotify playback device"]', 'no-such-device');
    assert(`document.querySelector('.settings-dialog').innerText.includes('No matches')`, 'Spotify output search must show a no-match state');
    run('press', 'Escape');
    run('wait', '--fn', '!document.querySelector("[role=listbox]")');
    run('click', '[aria-label="Open Spotify playback device"]');
    run('press', 'ArrowDown');
    run('press', 'Enter');
    assert(`document.querySelector('[aria-label="Spotify playback device"]').getAttribute('aria-expanded')==='false'`, 'Spotify device selection must support keyboard input');
    run('click', '#settings-tab-advanced');
    assert(`document.querySelector('#settings-tab-advanced').getAttribute('aria-selected')==='true' && document.querySelector('.settings-dialog .advanced')`, 'Advanced settings must be reachable');
    assert(`document.documentElement.scrollWidth<=innerWidth`, 'Settings must fit the window');
    capture(size, 'settings-advanced');
    evaluate(`window.__settingsWidth=document.querySelector('.advanced').getBoundingClientRect().width`);
    run('click', '.advanced > details:nth-of-type(1) summary');
    run('click', '.advanced > details:nth-of-type(2) summary');
    assert(`(() => { const section=document.querySelector('.advanced').getBoundingClientRect(); return [...document.querySelectorAll('.advanced > details')].every(details=>Math.abs(details.getBoundingClientRect().right-section.right)<1) && Math.abs(section.width-window.__settingsWidth)<1; })()`, 'Expanded settings dividers must span the section without scrollbar layout shifts');
    evaluate(`document.querySelector('.settings-dialog .content').scrollTop=9999`);
    assert(`(() => { const scroller=document.querySelector('.settings-dialog .content').getBoundingClientRect(); const button=document.querySelector('.advanced .detail-body button:last-child'); const r=button.getBoundingClientRect(); return r.bottom<=scroller.bottom-12 && button.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2)); })()`, 'The final settings action must remain reachable with bottom breathing room');
    capture(size, 'settings-advanced-expanded');
    run('click', '#settings-tab-spotify');
    assert(`document.querySelector('.settings-dialog .content').scrollTop===0`, 'Switching settings categories must start at the top');
    run('click', '#settings-tab-advanced');
    run('focus', button('Close settings'));
    for (let index=0; index<10; index++) run('press', 'Tab');
    assert(`!!document.activeElement.closest('.settings-dialog')`, 'Tab focus must stay inside Settings');
    run('press', 'q');
    assert(`!document.querySelector('.now-playing')`, 'Settings keys must not open the player behind the modal');
    run('click', button('Close settings'));
    assert(`!document.querySelector('.settings-dialog[open]') && document.activeElement.getAttribute('aria-label')==='Settings'`, 'X must close Settings and restore its visible trigger');
    run('click', button('Layout'));
    run('click', '.controls button[aria-pressed]');
    run('focus', '[aria-label="Album columns"] [role="slider"]');
    run('press', 'ArrowRight');
    assert(`document.querySelector('[aria-label="Album columns"] [role="slider"]').getAttribute('aria-valuenow')==='7'`, 'Advanced columns slider must answer keyboard input');
    run('press', 'ArrowLeft');
    capture(size, 'advanced-layout');
    run('click', '.controls button[aria-pressed]');
    assert(`!document.querySelector('.side') && !document.querySelector('.component-panel')`, 'Toolbar modes must replace stacked display menus and the theme drawer');
    run('click', button('Background'));
    assert(`!!document.querySelector('[role="radiogroup"][aria-label="Background"]') && !document.querySelector('[aria-label="Advanced grid size"]')`, 'Background must replace the secondary layout controls');
    assert(`document.querySelector('.bar-modes').getBoundingClientRect().right<=innerWidth && document.querySelector('.controls .group').getBoundingClientRect().right<=innerWidth`, 'Background mode must keep its toolbar and material strip within the viewport');
    capture(size, 'background-mode');
    run('click', button('Theme'));
    assert(`document.querySelectorAll('.browse [aria-label="Search library"]').length===1`, 'Search must have a single home');
    const scrollBeforeTheme = run('eval', 'document.querySelector(".scroll").scrollTop').trim();
    const iconSizes = [];
    for (const style of ['classic', 'neon', 'coss', 'studio']) {
      run('click', `.style-card[data-theme="${style}"]`);
      assert(`document.documentElement.dataset.components===${JSON.stringify(style)}`, 'Theme must apply');
      assert(`document.querySelector('.scroll').scrollTop === ${scrollBeforeTheme}`, 'Theme selection must preserve wall position');
      iconSizes.push(run('eval', 'JSON.stringify([document.querySelector("button[aria-label=Settings] svg").getBoundingClientRect().width,document.querySelector("button[aria-label=Settings] svg").getBoundingClientRect().height])').trim());
      capture(size, `components-${style}`);
    }
    if (new Set(iconSizes).size !== 1) throw new Error('Settings icons must be the same size in every theme');
    run('click', button('Back to library'));
    assert(`!document.querySelector('.secondary-controls')`, 'Back must close the secondary toolbar and retain the library');
    run('click', button('Theme'));
    evaluate('document.activeElement?.blur()');
    run('press', '/');
    run('wait', '200');
    assert(`document.activeElement.getAttribute('aria-label')==='Search library' && !document.querySelector('.secondary-controls')`, 'Search shortcut must return from Theme and focus the library search');
    run('press', 'Escape');
    evaluate('document.activeElement?.blur()');
    run('mouse', 'move', String(width / 2), String(height / 2));
    run('wait', '3200');
    run('hover', '.tile-wrap:first-child');
    run('click', '.tile-wrap:first-child .tile');
    run('wait', '500');
    assert(`Array.from(document.querySelectorAll('section')).every(e=>e.scrollWidth<=e.clientWidth)`, 'Track details must not overflow');
    capture(size, 'track-details');
    run('click', button('Back to music'));
    run('wait', '500');
    run('press', '/');
    run('fill', '[aria-label="Search library"]', 'Included song 1');
    run('wait', '.results .song-row');
    const commandsBeforeAdd = run('eval', 'window.__auditCommands.length').trim();
    run('click', '.results .song-row .add');
    assert(`window.__auditCommands.length===${commandsBeforeAdd}`, 'Catalog Add to queue must not start playback');
    run('wait', '.now-playing');
    assert(`document.querySelectorAll('.now-playing .song').length===3 && document.querySelector('.bar .btns button[aria-label="Play"]')`, 'Catalog Add to queue must reveal the appended occurrence while playback stays paused');
    run('press', 'Escape');
    run('mouse', 'move', String(width / 2), '4');
    run('wait', '200');
    run('fill', '[aria-label="Search result type"]', 'Songs');
    run('click', '[role="option"]');
    assert(`document.querySelector('[aria-label="Song results"]') && !document.querySelector('[aria-label="Albums results"]')`, 'Catalog result-type selection must narrow the results');
    capture(size, 'catalog-search');
    run('click', '.results .clear');
    run('wait', '.tile-wrap');
    assert(`!document.querySelector('.results') && document.querySelector('.bar .meta').innerText===${playingBeforeViews}`, 'Clearing catalog search must restore the wall and preserve playback');
    evaluate(`document.querySelector('.scroll').scrollTop=2000`);
    run('wait', '200');
    evaluate(`window.__beforeScroll=document.querySelector('.scroll').scrollTop; window.__beforeTitles=Array.from(document.querySelectorAll('.tile')).map(e=>e.getAttribute('aria-label')); window.__beforeQueue=document.querySelector('.bar .meta')?.innerText; window.__auditRefresh()`);
    run('wait', '200');
    assert(`document.querySelector('.scroll').scrollTop===window.__beforeScroll && JSON.stringify(Array.from(document.querySelectorAll('.tile')).map(e=>e.getAttribute('aria-label')))===JSON.stringify(window.__beforeTitles) && document.querySelector('.bar .meta')?.innerText===window.__beforeQueue`, 'Background refresh must preserve scroll, tile order and playback');
    assert(`document.documentElement.scrollWidth<=innerWidth`, 'Page must not overflow horizontally');
    evaluate(`document.activeElement?.blur(); window.__wallScroll=document.querySelector('.scroll').scrollTop; window.__wallTop=document.querySelector('.grid').getBoundingClientRect().top`);
    run('mouse', 'move', String(width / 2), String(height / 2));
    run('wait', '3200');
    assert(`getComputedStyle(document.querySelector('.browse')).opacity==='0'`, 'Top chrome must hide after inactivity');
    assert(`getComputedStyle(document.querySelector('.scroll')).paddingTop==='0px'`, 'Wall must not reserve space for chrome');
    capture(size, 'idle-wall');
    run('mouse', 'move', String(width / 2), '4');
    run('wait', '650');
    assert(`getComputedStyle(document.querySelector('.browse')).opacity==='1'`, 'Hovering the top edge must reveal chrome');
    assert(`document.querySelector('.scroll').scrollTop===window.__wallScroll && document.querySelector('.grid').getBoundingClientRect().top===window.__wallTop`, 'Chrome reveal must preserve wall and scroll position');
    run('wait', '3200');
    assert(`getComputedStyle(document.querySelector('.browse')).opacity==='1'`, 'Resting over chrome must keep it visible');
    capture(size, 'hover-chrome');
    run('focus', '[aria-label="Search library"]');
    run('mouse', 'move', String(width / 2), String(height / 2));
    run('wait', '3200');
    assert(`getComputedStyle(document.querySelector('.browse')).opacity==='1'`, 'Focused search must remain visible while idle');
    evaluate('document.activeElement?.blur()');
    run('wait', '3200');
    evaluate('document.querySelector(".scroll").scrollTop=0');
    run('wait', '300');
    assert(`!document.querySelector('.browse').classList.contains('hidden')`, 'Scrolling back to the top must reveal the toolbar');
    run('wait', '2100');
    assert(`document.querySelector('.browse').classList.contains('hidden')`, 'Scroll reveal must settle back to the unobstructed wall');
    run('mouse', 'move', String(width / 2), '35');
    run('wait', '350');
    run('focus', button('Library'));
    const commandsBeforeModes = run('eval', 'window.__auditCommands.length').trim();
    run('press', 'Tab');
    assert(`document.activeElement.getAttribute('aria-label')==='Library filters' && window.__auditCommands.length===${commandsBeforeModes}`, 'Tab must navigate toolbar choices without changing playback');
    run('press', 'Enter');
    assert(`!!document.querySelector('[aria-label="Filter by artist"]')`, 'Keyboard must activate toolbar modes');
    run('press', 'Escape');
    run('press', 'Escape');
    run('click', button('Settings'));
    run('click', '#settings-tab-spotify');
    run('click', '.connection .account button');
    run('wait', '--fn', 'document.querySelector(".connection-status").innerText.includes("Not connected")');
    assert(`!document.querySelector('.connection .account button') && document.querySelector('.spotify-settings').innerText.includes('Connect Spotify') && document.querySelector('.spotify-settings').innerText.includes('Saved library')`, 'Disconnect must show the disconnected state and retain the saved library');
    capture(size, 'settings-disconnected');
    run('click', button('Close settings'));
    results.push({ size, status: 'passed' });
    console.log(`${size}: passed`);
  }
} catch (error) {
  results.push({ status: 'failed', error: error.message });
  try { run('screenshot', path.join(output, 'failure.png')); await writeFile(path.join(output, 'failure-snapshot.txt'), run('snapshot')); } catch {}
  process.exitCode = 1;
} finally {
  await writeFile(path.join(output, 'results.json'), JSON.stringify({ automated: results, visualReview: 'pending; inspect screenshots against approved references' }, null, 2));
  try { run('close'); } catch {}
  console.log(`Audit artifacts: ${output}`);
}
