import { execFileSync } from 'node:child_process';
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

const output = path.resolve(import.meta.dirname, '../../../.audit-results', new Date().toISOString().replace(/[:.]/g, '-'));
await mkdir(output, { recursive: true });
const cli = process.env.MUSIC_AGENT_BROWSER || 'agent-browser';
const args = ['--session', 'music-regressions'];
let started = false;
const run = (...command) => {
  const env = { ...process.env };
  if (started) delete env.AGENT_BROWSER_EXECUTABLE_PATH;
  started = true;
  if (['click', 'focus'].includes(command[0]) && ['Library', 'Library filters', 'Layout', 'Background', 'Theme', 'Settings'].some(label => command[1] === `button[aria-label="${label}"]`)) {
    const expanded = execFileSync(cli, [...args, 'eval', 'document.querySelector(".bar-modes > button").getAttribute("aria-expanded")'], { encoding: 'utf8', timeout: 30000, env }).trim();
    if (!expanded.includes('true')) execFileSync(cli, [...args, 'click', 'button[aria-label="Choose toolbar mode"]'], { encoding: 'utf8', timeout: 30000, env });
  }
  return execFileSync(cli, [...args, ...command], { encoding: 'utf8', timeout: 30000, env });
};
const evaluate = code => run('eval', code);
const assert = (condition, message) => evaluate(`(() => { if (!(${condition})) throw new Error(${JSON.stringify(message)}); return 'PASS'; })()`);
const button = name => `button[aria-label="${name}"]`;
const capture = (size, name) => run('screenshot', path.join(output, `${size}-${name}.png`));
const results = [];
try {
  const viewports = [[1920,1080], [1440,900], [1024,768], [390,844]].filter(([width, height]) => !process.env.MUSIC_AUDIT_VIEWPORT || process.env.MUSIC_AUDIT_VIEWPORT === `${width}x${height}`);
  if (!viewports.length) throw new Error('Unknown MUSIC_AUDIT_VIEWPORT');
  for (const [width, height] of viewports) {
    const size = `${width}x${height}`;
    run('set', 'viewport', String(width), String(height));
    run('open', process.env.MUSIC_AUDIT_URL || 'http://127.0.0.1:4178');
    run('wait', '.tile-wrap');
    run('mouse', 'move', '0', '0');
    run('wait', '200');
    assert(`getComputedStyle(document.querySelector('.tile-info')).opacity === '0'`, 'Details must be hidden initially');
    evaluate('document.activeElement?.blur()');
    run('mouse', 'move', String(width / 2), String(height / 2));
    run('wait', '3200');
    run('hover', '.tile-wrap:first-child');
    run('wait', '200');
    assert(`getComputedStyle(document.querySelector('.tile-info')).opacity === '1'`, 'Hover must reveal details');
    assert(`(() => { const el=document.querySelector('.tile-actions button'); const r=el.getBoundingClientRect(); return el.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2)); })()`, 'Artwork must not obscure detail actions');
    run('mouse', 'move', '0', '0');
    run('focus', '.tile-wrap:first-child .tile-actions button[aria-label^="Show tracks"]');
    run('wait', '200');
    assert(`getComputedStyle(document.querySelector('.tile-info')).opacity === '1'`, 'Keyboard focus must reveal details');
    capture(size, 'card-focus');
    evaluate('document.activeElement?.blur()');
    run('mouse', 'move', String(width / 2), String(height / 2));
    run('wait', '3200');
    run('click', '.tile-wrap:first-child .tile');
    run('wait', '300');
    assert(`window.__auditCommands.some(c=>c[0]==='play')`, 'Cover must play included tracks');
    run('wait', '500');
    run('click', button('Pause'));
    run('click', button('Show songs'));
    run('wait', '350');
    assert(`document.querySelector('.now-playing .artwork img') !== null`, 'Now playing must show large artwork');
    assert(`getComputedStyle(document.querySelector('.bar')).getPropertyValue('--play-surface').trim() !== ''`, 'Player must share its artwork palette');
    assert(`document.documentElement.scrollWidth<=innerWidth`, 'Now playing must fit the viewport');
    capture(size, 'now-playing');
    run('click', '.now-playing .song:first-of-type .track-menu summary');
    assert(`document.querySelector('.now-playing .track-menu').open`, 'Track actions must open on demand');
    run('press', 'Escape');
    assert(`document.querySelector('.now-playing') && !document.querySelector('.now-playing .track-menu').open`, 'Escape must close track actions before the player');
    run('press', 'Escape');
    run('wait', '200');
    assert(`!document.querySelector('.now-playing') && document.activeElement.getAttribute('aria-label')==='Show songs'`, 'Escape must close now playing and restore focus');

    evaluate('document.activeElement?.blur()');
    run('press', 'ArrowRight');
    run('wait', '350');
    assert(`document.querySelector('.bar .meta b').textContent.includes('song 2')`, 'Right arrow must advance playback');
    run('press', 'ArrowLeft');
    run('wait', '350');
    assert(`document.querySelector('.bar .meta b').textContent.includes('song 1')`, 'Left arrow must return to the previous track');
    run('click', button('Pause'));
    evaluate('document.activeElement?.blur()');
    run('press', '/');
    assert(`document.activeElement.getAttribute('aria-label')==='Search library'`, 'Slash must reveal and focus search');
    run('press', 'q');
    assert(`document.activeElement.value==='q' && !document.querySelector('.now-playing')`, 'Typing shortcuts must enter text rather than open views');
    run('press', 'Escape');
    assert(`document.activeElement.value===''`, 'Escape in search must clear the query first');
    run('press', 'Escape');
    assert(`document.activeElement.getAttribute('aria-label')!=='Search library'`, 'Escape in empty search must exit it');
    evaluate('document.activeElement?.blur()');
    run('press', 'Control+k');
    assert(`document.activeElement.getAttribute('aria-label')==='Search library'`, 'Control K must focus search');
    run('press', 'Escape');
    evaluate('document.activeElement?.blur()');
    run('press', 'q');
    run('wait', '300');
    assert(`!!document.querySelector('.now-playing')`, 'Q must open the player');
    run('press', 'Escape');
    run('wait', '200');
    evaluate('document.activeElement?.blur()');
    run('press', 's');
    run('wait', '300');
    assert(`document.querySelector('.body h1').textContent==='Settings'`, 'S must open Settings');
    run('press', 'Escape');
    run('wait', '200');
    assert(`!document.querySelector('.body h1')`, 'Escape must close Settings');
    run('press', '?');
    assert(`!!document.querySelector('[aria-label="Keyboard shortcuts"]')`, 'Shortcut help must be discoverable');
    capture(size, 'keyboard-help');
    run('press', 'Escape');
    run('focus', button('Menu'));
    run('press', 'ArrowDown');
    assert(`document.activeElement.closest('[aria-label="Playback options"]')!==null`, 'Menu arrow key must open and focus its options');
    run('press', 'End');
    assert(`document.activeElement.getAttribute('aria-label')==='Random from the grid'`, 'End must focus the last playback option');
    run('press', 'Escape');
    assert(`document.activeElement.getAttribute('aria-label')==='Menu'`, 'Playback menu Escape must restore its trigger focus');
    const commandsBeforeDiscovery = run('eval', 'window.__auditCommands.length').trim();
    run('mouse', 'move', String(width / 2), '35');
    run('wait', '350');
    assert(`!document.querySelector('.browse').classList.contains('hidden')`, 'Approaching the top edge must reveal the toolbar before reaching the edge');
    run('click', '.discovery-action');
    assert(`document.querySelector('.discovered') !== null && window.__auditCommands.length === ${commandsBeforeDiscovery}`, 'Discovery must reveal a cover without starting playback');

    assert(`Math.abs((document.querySelector('.bar-content').getBoundingClientRect().left + document.querySelector('.bar-content').getBoundingClientRect().right) / 2 - innerWidth / 2)<1`, 'Active controls must stay centered');
    run('click', button('Choose toolbar mode'));
    assert(`document.querySelector('[aria-label="Choose toolbar mode"]').getAttribute('aria-expanded')==='true' && document.querySelector('.bar-content').hidden`, 'Selector must replace current controls');
    assert(`document.querySelector('.browse').getBoundingClientRect().height<=80`, 'Open selector must occupy one row at every screen size');
    assert(`document.querySelector('.mode-options').getBoundingClientRect().right < document.querySelector('[aria-label="Choose toolbar mode"]').getBoundingClientRect().left`, 'Mode choices must expand to the left of the button');
    run('mouse', 'move', String(width / 2), String(height / 2));
    run('wait', '3200');
    assert(`!document.querySelector('.browse').classList.contains('hidden')`, 'Open selector must pin the toolbar after pointer departure');
    run('click', button('Choose toolbar mode'));
    assert(`!document.querySelector('[aria-label="Filter by artist"]')`, 'Secondary filters must be hidden initially');
    run('click', button('Library filters'));
    run('fill', '[aria-label="Filter by artist"]', 'zzzz-no-artist');
    run('wait', '100');
    assert(`document.querySelector('[aria-label="Filter by artist"]').getAttribute('aria-expanded')==='true' && document.body.innerText.includes('No matches')`, 'Typing must open no-match results');
    run('press', 'Escape');
    assert(`document.querySelector('[aria-label="Filter by artist"]').value==='All artists'`, 'Escape must restore the selected label');
    run('fill', '[aria-label="Filter by artist"]', 'Bowie');
    capture(size, 'artist-dropdown');
    run('click', '[role="option"]');
    assert(`document.querySelector('[aria-label="Filter by artist"]').value==='David Bowie'`, 'Artist selection must apply');
    run('click', button('Reset filters'));
    run('click', button('Settings'));
    run('wait', '500');
    assert(`document.querySelector(${JSON.stringify(button('Settings'))}).getAttribute('aria-pressed')==='true'`, 'Settings must show selected state');
    capture(size, 'settings');
    assert(`document.querySelector('.body h2').textContent==='Appearance'`, 'Everyday appearance controls must come first');
    assert(`Array.from(document.querySelectorAll('.body details')).every(details=>!details.open)`, 'Secondary settings must start collapsed');
    run('click', '.body > section.advanced summary');
    run('scrollintoview', '.body > section.advanced');
    assert(`document.querySelector('.body > section.advanced details').open`, 'Advanced settings must be reachable');
    assert(`document.documentElement.scrollWidth<=innerWidth`, 'Settings must fit the window');
    run('click', button('Settings'));
    run('click', button('Layout'));
    run('click', '.controls button[aria-pressed]');
    run('focus', '[aria-label="Album columns"] [role="slider"]');
    run('press', 'ArrowRight');
    assert(`document.querySelector('[aria-label="Album columns"] [role="slider"]').getAttribute('aria-valuenow')==='4'`, 'Advanced columns slider must answer keyboard input');
    run('press', 'ArrowLeft');
    capture(size, 'advanced-layout');
    run('click', '.controls button[aria-pressed]');
    assert(`!document.querySelector('.side') && !document.querySelector('.component-panel')`, 'Toolbar modes must replace stacked display menus and the theme drawer');
    run('click', button('Background'));
    assert(`!!document.querySelector('[role="radiogroup"][aria-label="Background"]') && !document.querySelector('[aria-label="Grid size"]')`, 'Background must replace layout in the same toolbar');
    assert(`document.querySelector('.bar-modes').getBoundingClientRect().right<=innerWidth && document.querySelector('.controls .group').getBoundingClientRect().right<=innerWidth`, 'Background mode must keep its toolbar and material strip within the viewport');
    capture(size, 'background-mode');
    run('click', button('Theme'));
    assert(`document.querySelectorAll('.browse [aria-label="Search library"]').length===1`, 'Search must have a single home');
    const scrollBeforeTheme = run('eval', 'document.querySelector(".scroll").scrollTop').trim();
    const iconSizes = [];
    for (const [index, style] of [[1,'classic'],[3,'neon'],[4,'coss'],[2,'studio']]) {
      run('click', `.style-card:nth-of-type(${index})`);
      assert(`document.documentElement.dataset.components===${JSON.stringify(style)}`, 'Theme must apply');
      assert(`document.querySelector('.scroll').scrollTop === ${scrollBeforeTheme}`, 'Theme selection must preserve wall position');
      iconSizes.push(run('eval', 'JSON.stringify([document.querySelector("button[aria-label=Settings] svg").getBoundingClientRect().width,document.querySelector("button[aria-label=Settings] svg").getBoundingClientRect().height])').trim());
      capture(size, `components-${style}`);
    }
    if (new Set(iconSizes).size !== 1) throw new Error('Settings icons must be the same size in every theme');
    run('click', button('Back to toolbar selector'));
    assert(`document.querySelector('.bar-content').hidden && document.querySelector('[aria-label="Choose toolbar mode"]').getAttribute('aria-expanded')==='true'`, 'Back must restore the selector in the same row');
    run('click', button('Theme'));
    evaluate('document.activeElement?.blur()');
    run('press', '/');
    assert(`document.activeElement.getAttribute('aria-label')==='Search library' && !document.querySelector('.browse-row').hidden`, 'Search shortcut must return from Theme and focus the library search');
    run('press', 'Escape');
    evaluate('document.activeElement?.blur()');
    run('mouse', 'move', String(width / 2), String(height / 2));
    run('wait', '3200');
    run('hover', '.tile-wrap:first-child');
    run('click', '.tile-wrap:first-child button[aria-label^="Show tracks"]');
    run('wait', '500');
    assert(`Array.from(document.querySelectorAll('section')).every(e=>e.scrollWidth<=e.clientWidth)`, 'Track details must not overflow');
    capture(size, 'track-details');
    run('click', button('Close'));
    run('wait', '500');
    evaluate(`document.querySelector('.scroll').scrollTop=2000`);
    run('wait', '200');
    evaluate(`window.__beforeScroll=document.querySelector('.scroll').scrollTop; window.__beforeTitles=Array.from(document.querySelectorAll('.tile img')).map(e=>e.alt); window.__auditRefresh()`);
    run('wait', '200');
    assert(`document.querySelector('.scroll').scrollTop===window.__beforeScroll && JSON.stringify(Array.from(document.querySelectorAll('.tile img')).map(e=>e.alt))===JSON.stringify(window.__beforeTitles)`, 'Background refresh must preserve scroll and tile order');
    assert(`document.documentElement.scrollWidth<=innerWidth`, 'Page must not overflow horizontally');
    evaluate(`document.activeElement?.blur(); window.__wallScroll=document.querySelector('.scroll').scrollTop; window.__wallTop=document.querySelector('.grid').getBoundingClientRect().top`);
    run('mouse', 'move', String(width / 2), String(height / 2));
    run('wait', '3200');
    assert(`getComputedStyle(document.querySelector('.browse')).opacity==='0'`, 'Top chrome must hide after inactivity');
    assert(`getComputedStyle(document.querySelector('.scroll')).paddingTop==='0px'`, 'Wall must not reserve space for chrome');
    capture(size, 'idle-wall');
    run('mouse', 'move', String(width / 2), '4');
    run('wait', '650');
    assert(`getComputedStyle(document.querySelector('.browse')).opacity==='1'`, 'Hovering the top edge must reveal chrome');
    assert(`document.querySelector('.scroll').scrollTop===window.__wallScroll && document.querySelector('.grid').getBoundingClientRect().top===window.__wallTop`, 'Chrome reveal must preserve wall and scroll position');
    run('wait', '3200');
    assert(`getComputedStyle(document.querySelector('.browse')).opacity==='1'`, 'Resting over chrome must keep it visible');
    capture(size, 'hover-chrome');
    run('focus', '[aria-label="Search library"]');
    run('mouse', 'move', String(width / 2), String(height / 2));
    run('wait', '3200');
    assert(`getComputedStyle(document.querySelector('.browse')).opacity==='1'`, 'Focused search must remain visible while idle');
    evaluate('document.activeElement?.blur()');
    run('wait', '3200');
    evaluate('document.querySelector(".scroll").scrollTop=0');
    run('wait', '300');
    assert(`!document.querySelector('.browse').classList.contains('hidden')`, 'Scrolling back to the top must reveal the toolbar');
    run('wait', '2100');
    assert(`document.querySelector('.browse').classList.contains('hidden')`, 'Scroll reveal must settle back to the unobstructed wall');
    run('mouse', 'move', String(width / 2), '35');
    run('wait', '350');
    run('focus', button('Library'));
    run('press', 'ArrowRight');
    assert(`document.activeElement.getAttribute('aria-label')==='Library filters'`, 'Arrow keys must navigate toolbar modes rather than skip a song');
    run('press', 'Enter');
    assert(`!!document.querySelector('[aria-label="Filter by artist"]')`, 'Keyboard must activate toolbar modes');
    run('press', 'Escape');
    run('press', 'Escape');
    results.push({ size, status: 'passed' });
    console.log(`${size}: passed`);
  }
} catch (error) {
  results.push({ status: 'failed', error: error.message });
  try { run('screenshot', path.join(output, 'failure.png')); await writeFile(path.join(output, 'failure-snapshot.txt'), run('snapshot')); } catch {}
  process.exitCode = 1;
} finally {
  await writeFile(path.join(output, 'results.json'), JSON.stringify({ automated: results, visualReview: 'pending; inspect screenshots against approved references' }, null, 2));
  try { run('close'); } catch {}
  console.log(`Audit artifacts: ${output}`);
}
