import type { Track, Collection } from './music';
export type PlaybackOrigin = Pick<Collection, 'id' | 'rawId' | 'source' | 'kind' | 'title' | 'cover'>;
export type ListeningContext = { id: string; queue: Track[]; origin?: PlaybackOrigin; order: 'normal' | 'shuffle' | 'random'; permutation: number[] };
export type HistoryEntry = { id: string; context: ListeningContext; index: number; cursor: number; playedAt: number };
export type DesktopProfile = { name: string; label: string; directory: string; existing: boolean; portable: boolean };
export type DesktopStatus = {
  phase: 'setup' | 'starting' | 'ready' | 'error'; error: string; onboarding: boolean;
  url: string; username: string; password: string; frame: boolean;
  share?: { webPort: number; port: number; password: string };
  build: { dirty?: boolean; version: string; channel: string; commit: string; branch: string; builtAt: string; runUrl: string };
  profile: DesktopProfile; musicFolder: string; musicFolders: string[];
  defaultMusicFolder: string; defaultMusicFolderAvailable: boolean; source: string; canCopy: boolean;
};
export type ProfileEntry = { name: string; label: string; createdAt: number; setupComplete: boolean };
export type HistoryBatch = { version?: 1; scope: string; contexts: ListeningContext[]; entries: { id: string; contextId: string; index: number; cursor: number; playedAt: number }[]; importKey?: string };
export type HistoryPage = { entries: HistoryEntry[]; total: number; hasMore: boolean };
export const HISTORY_SCHEMA_VERSION: 1;
export function isStoredTrack(value: unknown): value is Track;
export function isListeningContext(value: unknown): value is ListeningContext;
export function validateHistoryRequest(method: string, args: unknown): unknown;
export function validateDesktopRequest(name: string, args: unknown[]): void;
